Repository arras-energy/gridlabd, pull requests merged in 2020-11, with the labels that each got.

#793 Fix subcommand template docs
  docs/Subcommand/Template.md
Labels: documentation

#791 Update online documentation
  docs/Subcommand/Trace.md
Labels: documentation

#807 Add support for direct math ops in global variables
  docs/GLM/Global/Expansion.md
  gldcore/autotest/test_global_var_expansion.glm
  gldcore/globals.cpp
Labels: bug

#802 Add support for parent class definition in loader
  gldcore/class.cpp
  gldcore/load.cpp
  gldcore/load.h
Labels: bug

#803 Add convert subcommand
  docs/Subcommand/Convert.md
  gldcore/scripts/Makefile.mk
  gldcore/scripts/gridlabd-convert
Labels: enhancement
