Repository arras-energy/gridlabd, pull requests merged in 2020-09, with the labels that each got.

#741 Update test_version_macro.glm
  gldcore/autotest/test_bare_class.glm
  gldcore/autotest/test_version_macro.glm
Labels: bug

#740 Allow python get_class() call during init phase
  gldcore/link/python/python.cpp
Labels: enhancement

#739 Add support for path parsing of global variables
  docs/GLM/Global/Filename.md
  docs/GLM/Global/Filepath.md
  docs/GLM/Global/Filetype.md
  gldcore/autotest/test_pathparser.glm
  gldcore/globals.cpp
  gldcore/load.cpp
Labels: enhancement

#731 Add outage costs
  docs/Module/Reliability/Cost.md
  reliability/Makefile.mk
  reliability/autotest/test_cost.glm
  reliability/autotest/test_cost_outage.csv
  reliability/cost.cpp
  reliability/cost.h
  reliability/init.cpp
Labels: enhancement

#743 Update random.cpp
  gldcore/random.cpp
Labels: bug

#736 Merge develop to master beauharnois-10
  .github/ISSUE_TEMPLATE/problem-report.md
  docs/Command/Rusage.md
  docs/GLM/Global/Filename.md
  docs/GLM/Global/Filepath.md
  docs/GLM/Global/Filetype.md
  docs/Global/Rusage_file.md
  docs/Global/Rusage_rate.md
  docs/Module/Reliability/Cost.md
  gldcore/autotest/test_bare_class.glm
  gldcore/autotest/test_pathparser.glm
  gldcore/autotest/test_rusage.glm
  gldcore/autotest/test_version_macro.glm
  gldcore/cmdarg.cpp
  gldcore/exec.cpp
  gldcore/globals.cpp
  gldcore/globals.h
  gldcore/link/python/python.cpp
  gldcore/load.cpp
  gldcore/random.cpp
  gldcore/version.h
  reliability/Makefile.mk
  reliability/autotest/test_cost.glm
  reliability/autotest/test_cost_outage.csv
  reliability/cost.cpp
  reliability/cost.h
  reliability/init.cpp
Labels: bug, documentation, enhancement

#748 Add support for python properties
  docs/GLM/Property/Python.md
  gldcore/autotest/test_python_property.glm
  gldcore/property.cpp
  gldcore/property.h
  gldcore/python_embed.cpp
  gldcore/python_embed.h
  gldcore/rt/gridlabd.h
Labels: documentation, enhancement

#747 Move subcommand help tests to autotest folder
  gldcore/autotest/test_library_help.glm
  gldcore/autotest/test_manual_help.glm
  gldcore/autotest/test_python_help.glm
  gldcore/autotest/test_validate_help.glm
Labels: bug

#746 Develop add optimize module
  docs/Module/Optimize.md
  docs/Module/Optimize/Simple.md
  modules.mk
  optimize/Makefile.mk
  optimize/autotest/test_extremum.glm
  optimize/autotest/test_maximum_err.glm
  optimize/autotest/test_minimum.glm
  optimize/init.cpp
  optimize/main.cpp
  optimize/simple.cpp
  optimize/simple.h
Labels: enhancement

#745 Develop fix rusage format error and add global rusage data
  docs/Global/Rusage_data.md
  docs/Global/Rusage_file.md
  docs/Global/Rusage_rate.md
  gldcore/exec.cpp
  gldcore/globals.cpp
  gldcore/globals.h
Labels: bug

#752 Develop add server control halt and stop commands
  docs/Server/Control.md
  gldcore/server.cpp
Labels: enhancement

#753 Update Library.md
  docs/Subcommand/Library.md
Labels: documentation

#751 Develop fix load phase tautology
  powerflow/load.cpp
Labels: bug

#750 Develop add python property access
  Makefile.am
  docs/Module/Python/Property.md
  docs/Tutorial/Python shadow class tutorial.ipynb
  docs/Tutorial/models/gridlabd.conf
  docs/Tutorial/models/house_0.glm
  docs/Tutorial/models/house_1.glm
  docs/Tutorial/models/meter_0.glm
  docs/Tutorial/models/meter_1.glm
  docs/Tutorial/models/model_0.glm
  docs/Tutorial/models/model_1.glm
  docs/Tutorial/models/model_100.glm
  docs/Tutorial/models/record_0.glm
  docs/Tutorial/models/record_1.glm
  docs/Tutorial/models/test.glm
  docs/Tutorial/models/thermostat.py
  gldcore/Makefile.mk
  gldcore/autotest/example.glm
  gldcore/autotest/example.py
  gldcore/autotest/test_python_property.glm
  gldcore/autotest/test_python_property.py
  gldcore/convert.cpp
  gldcore/converters/Makefile.mk
  gldcore/converters/json2png.py
  gldcore/converters/tmy32glm.py
  gldcore/gldcore.h
  gldcore/link/python/python.cpp
  gldcore/link/python/setup.py
  gldcore/main.cpp
  gldcore/object.cpp
  gldcore/object.h
  gldcore/property.cpp
  gldcore/python_embed.cpp
  gldcore/python_embed.h
  gldcore/python_property.cpp
  gldcore/python_property.h
  gldcore/random.cpp
Labels: enhancement
