Repository arras-energy/gridlabd, pull requests merged in 2021-08, with the labels that each got.

#967 Generalizing class location for table converter
  gldcore/converters/csv-table2glm-object.py
Labels: enhancement

#966 Add config info to mdb2glm converter
  gldcore/converters/mdb2glm.py
Labels: bug

#971 Fix geodata docs
  docs/Tutorial/Geodata.md
  gldcore/geodata/docs/Geodata.ipynb
  gldcore/geodata/docs/requirements.txt
  gldcore/scripts/Makefile.mk
  gldcore/scripts/gridlabd-requirements
Labels: documentation

#980 Fix gridlabd-library subcommand
  docs/Command/Library.md
  gldcore/autotest/test_library_include.glm
  gldcore/autotest/test_library_option.glm
  gldcore/cmdarg.cpp
  gldcore/cmdarg.h
  gldcore/load.cpp
  gldcore/load.h
  gldcore/scripts/gridlabd-library
Labels: bug

#970 Fix geodata table input
  .gitignore
  docs/Tutorial/Geodata.md
  gldcore/converters/autotest/table2glm_input.csv
  gldcore/converters/autotest/test_table2glm.glm
  gldcore/converters/autotest/test_table2glm_err.glm
  gldcore/converters/autotest/test_table2glm_noclass.glm
  gldcore/converters/autotest/test_table2glm_noname.glm
  gldcore/converters/csv-table2glm-object.py
  gldcore/converters/csv2glm.py
  gldcore/converters/json2html.py
  gldcore/geodata/docs/Geodata.ipynb
  gldcore/geodata/tutorial/.gitignore
  gldcore/geodata/tutorial/example_1.glm
  gldcore/geodata/tutorial/example_2.glm
  gldcore/geodata/tutorial/example_3.glm
  gldcore/geodata/tutorial/example_4.glm
  gldcore/geodata/tutorial/example_5.glm
  gldcore/geodata/tutorial/example_6.glm
  gldcore/geodata/tutorial/poles.csv
  gldcore/geodata/tutorial/positions.csv
  gldcore/scripts/autotest/test_geodata.glm
  gldcore/scripts/autotest/test_geodata.txt
  gldcore/scripts/gridlabd-convert
  gldcore/scripts/gridlabd-geodata
Labels: bug

#977 Change no-args to look for gridlabd-editor
  gldcore/cmdarg.cpp
  python_extras/Makefile.mk
  python_extras/gridlabd-editor.png
  python_extras/gridlabd-editor.py
Labels: bug

#732 Add support for input from RECS survey data
  Geodata.md
  docs/Tutorials/Geodata.md
  docs/Tutorials/Python shadow class tutorial.ipynb
  docs/Tutorials/Using_EIA_RECS_data.md
  docs/Tutorials/models/gridlabd.conf
  docs/Tutorials/models/house_0.glm
  docs/Tutorials/models/house_1.glm
  docs/Tutorials/models/meter_0.glm
  docs/Tutorials/models/meter_1.glm
  docs/Tutorials/models/model_0.glm
  docs/Tutorials/models/model_1.glm
  docs/Tutorials/models/model_100.glm
  docs/Tutorials/models/record_0.glm
  docs/Tutorials/models/record_1.glm
  docs/Tutorials/models/test.glm
  docs/Tutorials/models/thermostat.py
  gldcore/autotest/test_library_include.glm
  gldcore/converters/json2glm.py
  gldcore/geodata/Makefile.mk
  gldcore/geodata/tutorial/.gitignore
  gldcore/load.cpp
  gldcore/python_embed.cpp
  gldcore/scripts/gridlabd-plot
  python_extras/Makefile.mk
  python_extras/eia_recs.py
  tutorials/Geodata/example.glm
  tutorials/Geodata/example_1.glm
  tutorials/Geodata/example_2.glm
  tutorials/Geodata/example_3.glm
  tutorials/Geodata/example_4.glm
  tutorials/Geodata/example_5.glm
  tutorials/Geodata/example_6.glm
  tutorials/Geodata/path_example.csv
  tutorials/Geodata/poles.csv
  tutorials/Geodata/positions.csv
  tutorials/Geodata/tutorial.ipynb
  tutorials/README.md
  tutorials/Using_EIA_RECS_data/eia_recs_floorarea.glm
  tutorials/Using_EIA_RECS_data/eia_recs_floorarea.py
  tutorials/Using_EIA_RECS_data/eia_recs_floorarea_insulation.glm
  tutorials/Using_EIA_RECS_data/eia_recs_floorarea_insulation.py
  tutorials/Using_EIA_RECS_data/eia_recs_floorarea_temperature.glm
  tutorials/Using_EIA_RECS_data/eia_recs_floorarea_temperature.py
  tutorials/Using_EIA_RECS_data/tutorial.ipynb
  tutorials/requirements.txt
Labels: enhancement
