Repository arras-energy/gridlabd, pull requests merged in 2022-02, with the labels that each got.

#1034 Update setup-Linux-debian-9.sh
  build-aux/setup-Linux-debian-10.sh
  build-aux/setup-Linux-debian-9.sh
Labels: bug

#1091 Fix nsrdb_weather key management
  python_extras/nsrdb_weather.py
Labels: bug

#1089 Add timezone subcommand
  docs/GLM/Directive/Clock.md
  docs/Subcommand/Timezone.md
  gldcore/scripts/Makefile.mk
  gldcore/scripts/autotest/test_timezone.glm
  gldcore/scripts/gridlabd-timezone
  gldcore/scripts/requirements.txt
  gldcore/timestamp.cpp
  gldcore/tzinfo.txt
Labels: bug, enhancement

#1090 Update setup-Linux-debian-11.sh
  build-aux/setup-Linux-centos-8.sh
  build-aux/setup-Linux-debian-11.sh
Labels: enhancement
