Repository arras-energy/gridlabd, pull requests merged in 2022-01, with the labels that each got.

#1057 Update setup-Linux-centos-8.sh file
  build-aux/setup-Linux-centos-8.sh
  gldcore/scripts/autotest/test_matrix.glm
  gldcore/scripts/autotest/test_matrix_linalg.glm
  gldcore/scripts/autotest/test_matrix_matlib.glm
  gldcore/scripts/autotest/test_matrix_matrix.glm
  gldcore/scripts/autotest/test_matrix_random.glm
  install.sh
  requirements.txt
Labels: bug

#1015 Fix the processor allocation in docker
  docker/gridlabd.sh
Labels: bug

#1033 Update setup-Linux-amzn-2.sh
  README.md
  build-aux/setup-Linux-amzn-2.sh
Labels: bug

#1076 Remove temporary docker file
  Dockerfile_centos8
Labels: build

#1073 Develop add libinfo json
  docs/Command/Cite.md
  docs/Command/Globals.md
  docs/Command/Libinfo.md
  gldcore/cmdarg.cpp
  gldcore/debug.cpp
  gldcore/job.cpp
  gldcore/module.cpp
  gldcore/module.h
  gldcore/output.cpp
  gldcore/output.h
  gldcore/validate.cpp
Labels: enhancement

#1077 Fix parallel validation errors
  Makefile.am
  gldcore/autotest/test_config.glm
  gldcore/autotest/test_config_prefix.glm
  gldcore/autotest/test_config_relax.glm
  gldcore/autotest/test_library_include.glm
  gldcore/geodata/requirements.txt
  gldcore/scripts/Makefile.mk
  gldcore/scripts/gridlabd-library
  gldcore/scripts/gridlabd-lock
  gldcore/scripts/gridlabd-template
  gldcore/scripts/gridlabd-weather
  gldcore/scripts/requirements.txt
  module/optimize/autotest/test_extremum_opt.glm
  module/optimize/autotest/test_maximum_err.glm
  module/optimize/autotest/test_minimum.glm
  module/resilience/docs/requirements.txt
  requirements.txt
Labels: bug

#1064 Add support for #wait macro
  .gitignore
  docs/GLM/Macro/Start.md
  docs/GLM/Macro/Wait.md
  gldcore/autotest/test_wait.glm
  gldcore/autotest/test_wait_err.glm
  gldcore/load.cpp
  gldcore/load.h
Labels: enhancement

#1074 Develop fix sublime syntax
  Makefile.am
  docs/Command/Sublime_syntax.md
  gldcore/cmdarg.cpp
  gldcore/load.cpp
  gldcore/load.h
  utilities/Makefile.mk
  utilities/sublime/README.md
  utilities/sublime/gridlabd.sublime-syntax
Labels: bug

#1065 Fix new build warnings
  module/generators/windturb_dg.cpp
  module/powerflow/fault_check.cpp
  module/powerflow/line.cpp
  module/powerflow/link.cpp
  module/powerflow/node.cpp
  module/powerflow/solver_nr.cpp
  module/powerflow/solver_py.cpp
Labels: bug

#1054 Add maximum_runtime
  docs/Global/Maximum_runtime.md
  gldcore/exec.cpp
  gldcore/globals.cpp
  gldcore/globals.h
  gldcore/main.cpp
  gldcore/main.h
Labels: enhancement

#1055 Add transformer degradation factor
  docs/Module/Powerflow/Transformer.md
  module/powerflow/autotest/test_IEEE_13_FBS_degradation.glm
  module/powerflow/transformer.cpp
  module/powerflow/transformer.h
Labels: enhancement

#1086 Fix geodata vegetation credentials check error
  gldcore/geodata/geodata_vegetation.py
Labels: bug

#1085 Add nsrdb geodata package
  gldcore/geodata/Makefile.mk
  gldcore/geodata/geodata_weather.py
  python_extras/Makefile.mk
  python_extras/nsrdb_weather.py
Labels: enhancement
