Repository arras-energy/gridlabd, pull requests merged in 2022-03, with the labels that each got.

#1105 Add market data download tool
  docs/Utilities/Market_data.md
  gldcore/load.cpp
  python_extras/Makefile.mk
  python_extras/example/caiso_data.glm
  python_extras/example/isone_data.glm
  python_extras/market_data.py
Labels: enhancement

#1106 Add create_player tool
  docs/Utilities/Create_player.md
  python_extras/Makefile.mk
  python_extras/create_player.py
  python_extras/example/create_player.glm
  python_extras/example/power_panel.csv
Labels: enhancement

#1107 Add create filter utility
  docs/Utilities/Create_filter.md
  python_extras/Makefile.mk
  python_extras/create_filter.py
Labels: enhancement

#1113 Move geodata folder
  Makefile.am
  geodata/Makefile.mk
  geodata/autotest/test_datasets.glm
  geodata/autotest/unittest.sh
  geodata/geodata_address.py
  geodata/geodata_census.py
  geodata/geodata_distance.py
  geodata/geodata_elevation.py
  geodata/geodata_powerline.py
  geodata/geodata_powerline_cabletypes.csv
  geodata/geodata_utility.py
  geodata/geodata_vegetation.py
  geodata/geodata_weather.py
  geodata/requirements.txt
  gldcore/Makefile.mk
  gldcore/geodata/Makefile.mk
  gldcore/geodata/geodata.conf
Labels: build

#1115 Create python folder
  .gitignore
  Makefile.am
  gldcore/Makefile.mk
  gldcore/link/python/Makefile.mk
  python/Makefile.mk
  python/README.md
  python/autotest/test_external_callback.glm
  python/autotest/test_external_callback.py
  python/config_external.h
  python/examples/example_1/handlers.py
  python/examples/example_1/model.glm
  python/examples/example_2/handlers.py
  python/examples/example_2/main.py
  python/examples/example_2/model.glm
  python/examples/example_3/main.py
  python/examples/example_3/model.glm
  python/examples/example_3/x.csv
  python/examples/example_4/test_memory.glm
  python/examples/example_4/test_memory.py
  python/examples/example_4/test_memory_module.py
  python/gridlabd_python.py
  python/pstatus.py
  python/python.cpp
  python/python_gridlabd.py
  python/setup.py
  python/validate.py
Labels: build

#1116 Create runtime folder
  Makefile.am
  gldcore/Makefile.mk
  gldcore/rt/Makefile.mk
  runtime/Makefile.mk
  runtime/about.htm
  runtime/capacitor_b.png
  runtime/capacitor_g.png
  runtime/capacitor_k.png
  runtime/capacitor_r.png
  runtime/debugger.conf
  runtime/eula.htm
  runtime/favicon.ico
  runtime/feeder.py
  runtime/file_dialog.htm
  runtime/gnuplot.conf
  runtime/gridlabd.cnf
  runtime/gridlabd.conf
  runtime/gridlabd.css
  runtime/gridlabd.h
  runtime/gridlabd.htm
  runtime/gridlabd.jpg
  runtime/gridlabd.js
  runtime/gridlabd.rc
  runtime/gridlabd.syn
  runtime/kml_icons.pptx
  runtime/load_b.png
  runtime/load_g.png
  runtime/load_k.png
  runtime/load_r.png
  runtime/main.htm
  runtime/meter_g.png
  runtime/mingw.conf
  runtime/node_b.png
  runtime/node_g.png
  runtime/node_k.png
  runtime/node_r.png
  runtime/regulator_b.png
  runtime/regulator_g.png
  runtime/regulator_k.png
  runtime/regulator_r.png
  runtime/switch_b.png
  runtime/switch_g.png
  runtime/switch_k.png
  runtime/switch_r.png
  runtime/transformer_b.png
  runtime/transformer_g.png
  runtime/transformer_k.png
  runtime/transformer_r.png
  runtime/triplex_meter_b.png
  runtime/triplex_meter_g.png
  runtime/triplex_meter_k.png
  runtime/triplex_meter_r.png
  runtime/tzinfo.txt
  runtime/unitfile.txt
Labels: build

#1117 Update gridlabd-weather
  subcommands/gridlabd-weather
Labels: enhancement

#1125 Update Docker.md
  docs/Install/Docker.md
Labels: documentation
