Repository arras-energy/gridlabd, pull requests merged in 2023-10, with the labels that each got.

#114 Fix geodata subcommand address autotest
  subcommands/autotest/test_geodata_address.glm
  tools/autotest/test_server.glm
  tools/gldserver.py
Labels: bug

#113 Fix write macro
  runtime/gridlabd.h
  source/gridlabd.h
  source/load.cpp
  source/object.cpp
  source/object.h
Labels: bug

#122 Fix NOW pseudo-global to support date/time format
  docs/GLM/Global/Now.md
  source/globals.cpp
Labels: documentation, enhancement

#121 Add support for TMPFILE pseudo-global
  docs/GLM/Global/Tmpfile.md
  python/Makefile.mk
  python/setup.py
  source/Makefile.mk
  source/gldcore.h
  source/globals.cpp
  source/main.cpp
  source/tmpfile.cpp
  source/tmpfile.h
Labels: enhancement

#108 Update build system to allow separate workdir
  Makefile.am
  build.sh
  cloud/Makefile.mk
  configure.ac
Labels: enhancement

#124 Update setup.sh
  setup.sh
Labels: bug, build

#126 Add spida xlsx converter
  converters/Makefile.mk
  converters/autotest/test_object_opt.glm
  converters/xls-spida2csv-geodata.py
  converters/xlsx-spida2csv-geodata.py
  converters/xlsx2csv.py
  docs/Converters/Import/SpidaCalc.md
  docs/Converters/Import/Xls_files.md
  subcommands/gridlabd-convert
Labels: bug, documentation, enhancement

#128 Emergency fix to xlsx-spida2csv-geodata.py
  converters/xlsx-spida2csv-geodata.py
Labels: bug

#123 Patch mysql and distutils
  configure.ac
  converters/csv2glm.py
  converters/xlsx-spida2csv-geodata.py
  module/assert/assert.vcproj
  module/climate/climate.vcproj
  module/commercial/commercial.vcproj
  module/generators/generators.vcproj
  module/market/market.vcproj
  module/mysql/MYSQL_specific.vsprops
  module/mysql/database.h
  module/mysql/init.cpp
  module/mysql/main.cpp
  module/optimize/optimize.vcproj
  module/powerflow/autotest/test_pole.csv
  module/reliability/reliability.vcproj
  module/residential/residential.vcproj
  module/tape/tape.vcproj
  module/tape_file/tape_file.vcproj
  module/tape_memory/tape_memory.vcproj
  module/tape_plot/tape_plot.vcproj
  python/setup.py
  setup/darwin_20.sh
  setup/darwin_21.sh
  setup/darwin_22.sh
  setup/ubuntu_20.sh
  setup/ubuntu_22.sh
  source/tmpfile.cpp
Labels: bug, enhancement, build

#137 Mysql bugfix
  configure.ac
  module/mysql/collector.cpp
  module/mysql/database.cpp
  module/mysql/recorder.cpp
  setup/darwin_20.sh
  setup/darwin_21.sh
  setup/darwin_22.sh
Labels: build

#141 Update gridlabd-contributors
  subcommands/gridlabd-contributors
Labels: bug, documentation, enhancement

#144 Update convert.cpp
  source/convert.cpp
Labels: bug
